---
title: "Branch-Level"
author: "RN DR"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: united
    number_sections: true
    code_folding: hide
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 100%;
  margin-left: auto;
  margin-right: auto;
}

div.main-container {
  max-width: 100%;
}
</style>
```


```{r include=FALSE}
rm(list=ls())
library(data.table)
library(lfe)
library(stargazer)
library(ggplot2)
library(stringr)
library(stringi)
library(readxl)
library(DBI)
library(RSQLite)
library(dplyr)

source('https://raw.githubusercontent.com/dratnadiwakara/r-utilities/main/functions.R')
# library(quantmod)
data_path = 'D:/OneDrive/research-data/'
gc()
```



```{r}
# locations <- fread(paste0(data_path,"retail_store_visitor_locations.csv.gz"),sep="|")
# 
# poi_sod <- fread(paste0(data_path,"poi_sod_4.csv.gz"))
# poi_sod <- poi_sod[,c("CERT","UNINUMBR","NAMEFULL","usps_address","full_address_sod","LOCATION_NAME","PLACEKEY","match_type")]
# poi_sod[, NEW_PLACEKEY := gsub('-.*@', '@', PLACEKEY)]
# 
# poi_sod <- poi_sod[!duplicated(poi_sod[,c("NEW_PLACEKEY","UNINUMBR")])]
# poi_sod <- poi_sod[!grepl("Western Union",LOCATION_NAME)]
# poi_sod <- poi_sod[!grepl("Payday",LOCATION_NAME)]
# 
# poi_sod[,no_branches:=.N,by=UNINUMBR]
# poi_sod[,atm:=ifelse(grepl(" ATM",LOCATION_NAME),1,0)]
# 
# poi_sod <- poi_sod[no_branches==1 | atm==0]
# 
# poi_sod[,no_branches:=.N,by=UNINUMBR]
# 
# poi_sod <- poi_sod[!(no_branches > 1 & tolower(substr(NAMEFULL, 1, 1)) != tolower(substr(LOCATION_NAME, 1, 1)))]
# poi_sod[,no_branches:=.N,by=UNINUMBR]
# poi_sod[,bank:=ifelse(grepl(" bank",tolower(LOCATION_NAME)),1,0)]
# 
# setorder(poi_sod,UNINUMBR,-bank)
# 
# poi_sod <- poi_sod[!duplicated(poi_sod$UNINUMBR)]
# 
# poi_sod <- merge(poi_sod,locations[,c("PLACEKEY","STORE_ID")])
# 
# poi_sod <- poi_sod[,c("UNINUMBR","NEW_PLACEKEY","STORE_ID")]
# 
# 
# sod <- fread("C:/Users/dratnadiwakara2/Documents/OneDrive - Louisiana State University/Raw Data/SOD/data/ALL_2022.csv",select = c("UNINUMBR","CERT","RSSDID","ASSET","DEPSUMBR","STCNTYBR","RSSDHCR","ZIPBR","SIMS_LATITUDE","SIMS_LONGITUDE"))
# sod[,DEPSUMBR:=str_remove_all(DEPSUMBR,",")]
# sod[,DEPSUMBR:=as.numeric(DEPSUMBR)]
# sod[,ASSET:=str_remove_all(ASSET,",")]
# sod[,ASSET:=as.numeric(ASSET)]
# sod[,statefips:=floor(STCNTYBR/1000)]
# sod[,statefips:=str_pad(statefips,2,"left","0")]
# 
# 
# 
# branches <- merge(sod,poi_sod,by="UNINUMBR",all.x=T)
# branches <- branches[!is.na(STORE_ID)]
# branches[,bank_size:=ifelse(ASSET<1e6,"1. Less than 1b",ifelse(ASSET<1e7,"2. 1 to 10b",ifelse(ASSET<5e7,"3. 10 to 50b",ifelse(ASSET<25e7,"4. 50 to 250b","5. More than 250b"))))]
# setorder(branches,bank_size)
# 
# 
# 
# visits <- fread(paste0(data_path,"retail_store_visitor_visits.csv.gz"),sep="|")
# 
# visits_2021 <- visits[year(MONTH_STARTING)==2021]
# visits_2021 <- visits_2021[,.(visits_2021=sum(TOTAL_VISITS)),by=STORE_ID]
# visits_2022 <- visits[year(MONTH_STARTING)==2022]
# visits_2022 <- visits_2022[,.(visits_2022=sum(TOTAL_VISITS)),by=STORE_ID]
# visits_change <- merge(visits_2021,visits_2022,by="STORE_ID")
# visits_change[,change_visits:=visits_2022/visits_2021-1]
# visits <- visits[year(MONTH_STARTING)==2019]
# 
# 
# education <- fread("C:/Users/dratnadiwakara2/Downloads/temp_dewey/retail_store_visitor_VISITOR_EDUCATIONAL_ATTAINMENT.csv",sep="|",quote = "\"")
# education <- education[index %in% visits$index]
# # setnames(education,"\"VISITOR_EDUCATIONAL_ATTAINMENT","VISITOR_EDUCATIONAL_ATTAINMENT")
# # setnames(education,"STORE_ID\"","STORE_ID")
# # education[, STORE_ID := gsub('"', '', STORE_ID)]
# # education[,VISITOR_EDUCATIONAL_ATTAINMENT:= gsub('"', '', VISITOR_EDUCATIONAL_ATTAINMENT)]
# 
# education <- merge(education,visits[,c("index","STORE_ID","TOTAL_VISITS")],by=c("index","STORE_ID"))
# education[,no_visits:=no_visits*TOTAL_VISITS/100]
# 
# education <- education[,.(no_visits=sum(no_visits)),by=.(STORE_ID,VISITOR_EDUCATIONAL_ATTAINMENT)]
# education[,college_or_higher:=ifelse(VISITOR_EDUCATIONAL_ATTAINMENT %in% c("AssocDegree","BachDegree","DoctDegree","MastDegree","ProfSchDegree"),1,0)]
# 
# education[,total_visits:=sum(no_visits,na.rm=T),by=STORE_ID]
# education <- education[college_or_higher==1]
# 
# education <- education[,.(college_or_higher=sum(no_visits),total_visits=median(total_visits)),by=STORE_ID]
# 
# education[,college_or_higher_frac:=college_or_higher/total_visits]
# 
# education <- education[,c("STORE_ID","college_or_higher_frac")]
# 
# 
# income <- fread("C:/Users/dratnadiwakara2/Downloads/temp_dewey/retail_store_visitor_VISITOR_HOUSEHOLD_INCOME.csv",sep="|")
# income <- income[index %in% visits$index]
# income[, c('lower_bound', 'upper_bound') := tstrsplit(gsub("USD|over,", "", VISITOR_HOUSEHOLD_INCOME), ",")]
# 
# income[, c('lower_bound', 'upper_bound') := lapply(.SD, as.numeric), .SDcols = c('lower_bound', 'upper_bound')]
# 
# income[, income_mid := (lower_bound + upper_bound) / 2]
# income[,income_mid:=ifelse(VISITOR_HOUSEHOLD_INCOME=="over,200000",250000,income_mid)]
# 
# income <- merge(income,visits[,c("index","STORE_ID","TOTAL_VISITS")],by=c("index","STORE_ID"))
# income[,no_visits:=no_visits*TOTAL_VISITS/100]
# 
# income <- income[,.(no_visits=sum(no_visits,na.rm=T)),by=.(income_mid,STORE_ID)]
# income[,total_visits:=sum(no_visits),by=STORE_ID]
# income[,wa_income:=no_visits*income_mid/total_visits]
# 
# income <- income[,.(household_income=sum(wa_income)),by=STORE_ID]
# 
# 
# age <- fread("C:/Users/dratnadiwakara2/Downloads/temp_dewey/retail_store_visitor_VISITOR_AGE_RANGE.csv.gz",sep="|")
# age <- age[index %in% visits$index]
# 
# age[, c('lower_bound', 'upper_bound') := tstrsplit(VISITOR_AGE_RANGE, ",")]
# 
# age[, c('lower_bound', 'upper_bound') := lapply(.SD, as.numeric), .SDcols = c('lower_bound', 'upper_bound')]
# age[, age_mid := (lower_bound + upper_bound) / 2]
# age[, age_mid := ifelse(VISITOR_AGE_RANGE=="20",20,ifelse(VISITOR_AGE_RANGE=="21",21,ifelse(VISITOR_AGE_RANGE=="85pl",85,age_mid)))]
# 
# age <- merge(age,visits[,c("index","STORE_ID","TOTAL_VISITS")],by=c("index","STORE_ID"))
# age[,no_visits:=no_visits*TOTAL_VISITS/100]
# 
# age <- age[,.(no_visits=sum(no_visits,na.rm=T)),by=.(age_mid,STORE_ID)]
# age[,total_visits:=sum(no_visits),by=STORE_ID]
# age[,wa_age:=no_visits*age_mid/total_visits]
# 
# age <- age[,.(age=sum(wa_age)),by=STORE_ID]
# 
# 
# psy <- fread("C:/Users/dratnadiwakara2/Downloads/temp_dewey/retail_store_visitor_VISITOR_PSYCHOGRAPHIC_PROFILES.csv",sep="|")
# psy <- psy[index %in% visits$index]
# 
# 
# psy <- merge(psy,visits[,c("index","STORE_ID","TOTAL_VISITS")],by=c("index","STORE_ID"))
# psy[,no_visits:=no_visits*TOTAL_VISITS/100]
# 
# psy <- psy[,.(no_visits=sum(no_visits,na.rm=T)),by=.(VISITOR_PSYCHOGRAPHIC_PROFILES,STORE_ID)]
# psy[,total_visits:=sum(no_visits),by=STORE_ID]
# psy[,wa_psy:=no_visits*VISITOR_PSYCHOGRAPHIC_PROFILES/total_visits]
# 
# psy <- psy[,.(psy_profile=sum(wa_psy)),by=STORE_ID]
# 
# 
# branch_df <- merge(branches,education,by="STORE_ID")
# branch_df <- merge(branch_df,income,by="STORE_ID")
# branch_df <- merge(branch_df,age,by="STORE_ID")
# branch_df <- merge(branch_df,psy,by="STORE_ID")
# branch_df <- merge(branch_df,visits_change,by="STORE_ID",all.x=T)
# 
# retail_visits_branch_df <- copy(branch_df)
# saveRDS(retail_visits_branch_df,paste0(data_path,"retail_visits_branch_df.rds"))
# rm(list=c("age","branch_df","branches","education","income","locations","poi_sod",
# "psy","retail_visits_branch_df","sod","visits","visits_2021","visits_2022","visits_change"))
```

```{r}
retail_visits_branch_df <- readRDS(paste0(data_path,"Dewey/retail_visits_branch_df.rds"))
setnames(retail_visits_branch_df,c("household_income","college_or_higher_frac","age"),c("retail_income","retail_education","retail_age"))
```


```{r}
poi_sod <- fread(paste0(data_path,"Dewey/poi_sod_4.csv.gz"))
poi_sod <- poi_sod[,c("CERT","UNINUMBR","NAMEFULL","usps_address","full_address_sod","LOCATION_NAME","PLACEKEY","match_type")]
poi_sod[, NEW_PLACEKEY := gsub('-.*@', '@', PLACEKEY)]

poi_sod <- poi_sod[!duplicated(poi_sod[,c("NEW_PLACEKEY","UNINUMBR")])]
poi_sod <- poi_sod[!grepl("Western Union",LOCATION_NAME)]
poi_sod <- poi_sod[!grepl("Payday",LOCATION_NAME)]

poi_sod[,no_branches:=.N,by=UNINUMBR]
poi_sod[,atm:=ifelse(grepl(" ATM",LOCATION_NAME),1,0)]

poi_sod <- poi_sod[no_branches==1 | atm==0]

poi_sod[,no_branches:=.N,by=UNINUMBR]

poi_sod <- poi_sod[!(no_branches > 1 & tolower(substr(NAMEFULL, 1, 1)) != tolower(substr(LOCATION_NAME, 1, 1)))]
poi_sod[,no_branches:=.N,by=UNINUMBR]
poi_sod[,bank:=ifelse(grepl(" bank",tolower(LOCATION_NAME)),1,0)]

setorder(poi_sod,UNINUMBR,-bank)

poi_sod <- poi_sod[!duplicated(poi_sod$UNINUMBR)]

poi_sod <- poi_sod[,c("UNINUMBR","NEW_PLACEKEY","match_type")]

# poi_sod <- poi_sod[usps_address != ""]
```



```{r}
sod <- fread(paste0(data_path,"SOD/data/ALL_2022.csv"),select = c("UNINUMBR","CERT","RSSDID","ASSET","DEPSUMBR","STCNTYBR","RSSDHCR","ZIPBR","SIMS_LATITUDE","SIMS_LONGITUDE"))
sod[,DEPSUMBR:=str_remove_all(DEPSUMBR,",")]
sod[,DEPSUMBR:=as.numeric(DEPSUMBR)]
sod[,ASSET:=str_remove_all(ASSET,",")]
sod[,ASSET:=as.numeric(ASSET)]
sod[,statefips:=floor(STCNTYBR/1000)]
sod[,statefips:=str_pad(statefips,2,"left","0")]
```




```{r}
#DSS2021 p1136
hhi <- sod[,.(deposits = sum(DEPSUMBR,na.rm=T)),by=.(RSSDID,STCNTYBR)]
hhi[,total_deposits:=sum(deposits,na.rm = T),by=.(STCNTYBR)]
hhi[,deposit_share:=deposits/total_deposits]
hhi[,deposit_share:=deposit_share*deposit_share]
hhi <- hhi[,.(deposits_state_hhi=sum(deposit_share)),by=STCNTYBR]

bank_hhi <- sod[,c("RSSDID","STCNTYBR")]
bank_hhi <- data.table(bank_hhi)
bank_hhi <- bank_hhi[,.(no_branches=.N),by=.(RSSDID,STCNTYBR)]
bank_hhi <- bank_hhi[!duplicated(bank_hhi[,c("RSSDID","STCNTYBR")])]
bank_hhi <- merge(bank_hhi,hhi,by="STCNTYBR")
bank_hhi[,total_branches:=.N,by=RSSDID]
bank_hhi[,w_hhi:=no_branches*deposits_state_hhi]
hhi <- bank_hhi[,.(sum_w_hhi=sum(w_hhi),no_branches=median(total_branches)),by=RSSDID]

hhi[,bank_hhi:=sum_w_hhi/no_branches]
hhi <- hhi[,c("bank_hhi","RSSDID")]
```


```{r}
sod <- merge(sod,poi_sod,by="UNINUMBR",all.x=T)
sod[,match:=ifelse(is.na(NEW_PLACEKEY),0,1)]

sod[,bank_size:=ifelse(ASSET<1e6,"1. Less than 1b",ifelse(ASSET<1e7,"2. 1 to 10b",ifelse(ASSET<5e7,"3. 10 to 50b",ifelse(ASSET<25e7,"4. 50 to 250b","5. More than 250b"))))]

setorder(sod,bank_size)
```


```{r}
yrs <- as.character(2020:2021)
hmda <- list()
i=1
for(yr in yrs) {
  print(yr)
  hmda_con <- dbConnect(RSQLite::SQLite(), paste0("D:/OneDrive/research-data/HMDA/db/depositor_chars_",yr,"_lar.db"))
  hmda[[i]] <- data.table(dbGetQuery(hmda_con,
                                     paste0("select
                                                activity_year asofdate,
                                                loan_purpose purposeofloan,
                                                census_tract censustract
                                            from tb_",yr,"_lar where 
                                            occupancy_type=1 and action_taken=1")))
  i=i+1
  dbDisconnect(hmda_con)
}
hmda <- rbindlist(hmda)
hmda <- data.table(hmda)
gc()

hmda[,refinance:=ifelse(purposeofloan==1,0,1)]

hmda_summary <- hmda[,.(no_refinance=sum(refinance),no_loans=.N),by=censustract]

new_hmda_summary = copy(hmda_summary)
new_hmda_summary[,censustract:=paste0(substr(censustract,1,10),'0')]
new_hmda_summary <- new_hmda_summary[, lapply(.SD, sum), by = censustract, .SDcols = -"censustract"]
new_hmda_summary <- new_hmda_summary[!censustract %in% hmda_summary$censustract]

hmda_summary <- rbind(hmda_summary,new_hmda_summary)
```

```{r}
acs_block_data_file <- paste0(data_path,"Dewey/acs_tract_data_2.csv.gz")

asc_block_data <- fread(acs_block_data_file, header = TRUE)

asc_block_data[, `:=`(
  state = str_pad(state,width = 2,side = "left",pad = "0"),
  county =str_pad(county,width = 3,side = "left",pad = "0"),
  tract =str_pad(tract,width = 6,side = "left",pad = "0")
)]

# Replace negative values with NaN in specific columns
cols_to_replace <- c(
  "median_age",
  "median_income_last_12_months",
  "aggregate_family_income"
)

asc_block_data[, (cols_to_replace) := lapply(.SD, function(x) ifelse(x < 0, NA, x)), .SDcols = cols_to_replace]

# Create the 'censustract' column
asc_block_data[, censustract := paste0(state, county, tract)]

# Calculate additional columns
asc_block_data[, mean_family_income := aggregate_family_income / no_of_households]
asc_block_data[, white_fraction := population_race_white / population_race_base]
asc_block_data[, english_speaking_frac := households_language_english / households_language_base]
asc_block_data[, spanish_speaking_frac := households_language_spanish / households_language_base]
asc_block_data[, internet_frac := households_internet_yes / households_internet_base]
asc_block_data[, computer_frac := households_computer_yes / households_computer_base]
asc_block_data[, under_19_frac := population_by_age_base_under_19 / population_by_age_base]
asc_block_data[, over_65_frac := population_by_age_base_65_older / population_by_age_base]
asc_block_data[, below_poverty_frac := poverty_status_below / poverty_status_base]
asc_block_data[, food_stamp_frac := received_food_stamps_snap_yes / received_food_stamps_snap_base]
asc_block_data[, owner_occ_frac := housing_units_occupancy_own / housing_units_occupancy_base]
asc_block_data[, home_with_mtg_frac := housing_units_with_a_mortgage / housing_units_mortgage_base]
asc_block_data[, college_or_higher_frac := education_college_or_higher / education_base]
asc_block_data[, less_than_high_school_frac := education_less_than_high_school / education_base]

# Select desired columns
selected_columns <- c(
  'censustract',
  'median_age',
  'median_income_last_12_months',
  'mean_family_income',
  'white_fraction',
  'travel_time_to_work',
  'spanish_speaking_frac',
  'english_speaking_frac',
  'internet_frac',
  'computer_frac',
  'under_19_frac',
  'over_65_frac',
  'below_poverty_frac',
  'food_stamp_frac',
  'owner_occ_frac',
  'college_or_higher_frac',
  'less_than_high_school_frac'
)

acs_housing_units <- asc_block_data[,c("housing_units_with_a_mortgage","censustract")]
acs_housing_units <- acs_housing_units[,.(housing_units_with_a_mortgage=sum(housing_units_with_a_mortgage,na.rm=T)),by=censustract]

new_acs_housing_units <- copy(acs_housing_units)
new_acs_housing_units[,censustract:=paste0(substr(censustract,1,10),'0')]
new_acs_housing_units <- new_acs_housing_units[,.(housing_units_with_a_mortgage=sum(housing_units_with_a_mortgage,na.rm=T)),by=censustract]
new_acs_housing_units <- new_acs_housing_units[!censustract %in% acs_housing_units$censustract]
acs_housing_units <- rbind(acs_housing_units,new_acs_housing_units)

acs <- asc_block_data[, ..selected_columns]

new_acs = copy(acs)
new_acs[,censustract:=paste0(substr(censustract,1,10),'0')]
new_acs <- new_acs[, lapply(.SD, mean), by = censustract, .SDcols = -"censustract"]
new_acs <- new_acs[!censustract %in% acs$censustract]

acs <- rbind(acs,new_acs)
acs[, (names(acs)) := lapply(.SD, function(x) replace(x, is.infinite(x), NA)), .SDcols = names(acs)]
acs <- merge(acs,acs_housing_units,by="censustract")

acs <- merge(acs,hmda_summary,by="censustract",all.x=T)
acs[,refinance_rate:=no_refinance/housing_units_with_a_mortgage]
acs[,refinance_rate:=ifelse(is.finite(refinance_rate) & refinance_rate<1,refinance_rate,NA)]
```


```{r}
# this data is from : https://www.irs.gov/statistics/soi-tax-stats-individual-income-tax-statistics-2019-zip-code-data-soi
irs <-fread(paste0(data_path,"Dewey/19zpallagi.csv"),select = c("zipcode","N1","N00200","N00600","N00900","N01000")) #no_returns,no_returns_salaries,no_returns_dividend,no_returns_business,no_returns_captial_gain
setnames(irs,
         c("N1","N00200","N00600","N00900","N01000"),
         c("no_returns","no_returns_salaries","no_returns_dividend","no_returns_business","no_returns_captial_gain"))

irs <- irs[, lapply(.SD, function(x) sum(x, na.rm = TRUE)), by = zipcode]


irs[,salary_frac:=no_returns_salaries/no_returns]
irs[,dividend_frac:=no_returns_dividend/no_returns]
irs[,business_frac:=no_returns_business/no_returns]
irs[,capital_gain_frac:=no_returns_captial_gain/no_returns]

tract_zip <- fread(paste0(data_path,"Crosswalk Files/TRACT_ZIP_032016.csv"))
tract_zip[,TRACT:=as.character(TRACT)]
tract_zip[,TRACT:=str_pad(TRACT,11,"left","0")]
setorder(tract_zip,TRACT,-RES_RATIO)

tract_zip <- tract_zip[!duplicated(tract_zip$TRACT)]
tract_zip <- tract_zip[,c("TRACT","ZIP")]

irs <- merge(irs,tract_zip,by.x="zipcode",by.y="ZIP")
irs <- irs[,c("TRACT","salary_frac","dividend_frac","business_frac","capital_gain_frac")]

acs <- merge(acs,irs,by.x="censustract",by.y="TRACT",all.x=T)
```


```{r}
visits_file = paste0(data_path,'Dewey/cbgs_place_month_visits_count20190101_20200301.csv.gz')

visits <- fread(visits_file)
visits[,censustract:=substr(CBGS,1,11)]
visits[,CBGS:=NULL]
visits[, NEW_PLACEKEY := gsub('-[^@]+@', '@', PLACEKEY)]

visits_sum <- visits[,.(no_visits=sum(no_visits,na.rm=T)),by=.(censustract,NEW_PLACEKEY,DATE_RANGE_START)]
```

```{r}
visits_merged <- merge(visits_sum,acs,by="censustract")
gc()
```


```{r}
exclude_cols <- c("NEW_PLACEKEY", "DATE_RANGE_START","no_visits","censustract")

place_visitor_wa <- visits_merged[, lapply(.SD, weighted.mean, w = no_visits, na.rm = TRUE), by = .(NEW_PLACEKEY, DATE_RANGE_START), .SDcols = setdiff(names(visits_merged), exclude_cols)]

place_visitor_wa <- place_visitor_wa[NEW_PLACEKEY %in% sod$NEW_PLACEKEY]
place_visitor_wa <- merge(place_visitor_wa,sod,by="NEW_PLACEKEY")

```


```{r}
visits_summary <- fread(paste0(data_path,"Dewey/place_month_visit_summary20190101_20200301.csv.gz"))
visits_summary[, NEW_PLACEKEY := gsub('-[^@]+@', '@', PLACEKEY)]
visits_summary <- visits_summary[NEW_PLACEKEY %in% sod$NEW_PLACEKEY]

visits_summary <- visits_summary[,.(RAW_VISIT_COUNTS=sum(RAW_VISIT_COUNTS,na.rm=T),
                                    RAW_VISITOR_COUNTS = sum(RAW_VISITOR_COUNTS,na.rm=T),
                                    DISTANCE_FROM_HOME = mean(DISTANCE_FROM_HOME,na.rm=T),
                                    MEDIAN_DWELL = mean(MEDIAN_DWELL,na.rm=T),
                                    android = sum(android,na.rm=T),
                                    ios = sum(ios,na.rm=T)),
                                 by=.(NEW_PLACEKEY,DATE_RANGE_START)]


place_visitor_wa <- merge(place_visitor_wa,visits_summary,by=c("NEW_PLACEKEY","DATE_RANGE_START"))

place_visitor_wa[,android_pct:=android/(ios+android+1)]
place_visitor_wa[,deposits_per_visitor:=DEPSUMBR/(RAW_VISITOR_COUNTS+1)]
```


```{r}
website_visits <- readRDS(paste0(data_path,"Dewey/web_visits_2021.rds"))

physical_visits <- fread(paste0(data_path,"Dewey/place_month_visit_summary20210101_20221201.csv.gz"))
physical_visits <- physical_visits[year(DATE_RANGE_START)==2021]
physical_visits[, NEW_PLACEKEY := gsub('-[^@]+@', '@', PLACEKEY)]
physical_visits <- merge(physical_visits,sod,by="NEW_PLACEKEY")
physical_visits <- physical_visits[,.(branch_visits=sum(RAW_VISIT_COUNTS)),by=RSSDID]

website_visits <- merge(website_visits,physical_visits,by.x="IDRSSD",by.y="RSSDID")
website_visits[,web_branch_ratio:=web_visits_2021/branch_visits]
website_visits[,web_branch_pctile:=ntile(web_branch_ratio,100)]
website_visits <- website_visits[,c("web_branch_pctile","IDRSSD")]
```

```{r}
place_visitor_wa <- merge(place_visitor_wa,website_visits,by.x="RSSDID",by.y="IDRSSD",all.x=T)
```

```{r}
variables <- c( 'median_age',
  'median_income_last_12_months',
  'mean_family_income',
  'white_fraction',
  'travel_time_to_work',
  'spanish_speaking_frac',
  'english_speaking_frac',
  'internet_frac',
  'computer_frac',
  'under_19_frac',
  'over_65_frac',
  'below_poverty_frac',
  'food_stamp_frac',
  'owner_occ_frac',
  'college_or_higher_frac',
  'less_than_high_school_frac',
  'DISTANCE_FROM_HOME',
  'MEDIAN_DWELL',
  'salary_frac',
  'business_frac',
  'dividend_frac',
  'capital_gain_frac',
  'refinance_rate',
  'web_branch_pctile',
  'ASSET')
```


```{r}
branch_2019 <- place_visitor_wa[, lapply(.SD, mean, na.rm = TRUE), by = UNINUMBR, .SDcols = variables]
```


```{r}
retail_acs <- merge(branch_2019[,c("UNINUMBR","college_or_higher_frac","mean_family_income","median_age")],
                    retail_visits_branch_df[,c("UNINUMBR","retail_income","retail_education","retail_age")],
                    by="UNINUMBR")
```

```{r}
generate_lm_plot <- function(data, x_var, y_var, xlab, ylab) {
  cor_value <- cor(data[[x_var]], data[[y_var]], use = "complete.obs")
  
  g <- ggplot(data, aes_string(x = x_var, y = y_var)) +
    geom_point() +
    geom_smooth(method = "lm") +
    labs(x = xlab, y = ylab) +
    theme_minimal() +
    theme(legend.position = "bottom", legend.title = element_blank()) +
    annotate("text", x = min(data[[x_var]]), y = max(data[[y_var]]), label = paste("Correlation :", round(cor_value, 3)), hjust = 0, vjust = 1, size = 4)

  print(g)
  
}

generate_lm_plot(retail_acs, "retail_income", "mean_family_income", "Income (retail visits)", "Income (census tract)")
generate_lm_plot(retail_acs, "retail_education", "college_or_higher_frac", "College (retail visits)", "College (census tract)")
# generate_lm_plot(retail_acs, "retail_age", "median_age", "Income (retail)", "Income (census tract)")
```

```{r}
sod_2021 <- fread(paste0(data_path,"SOD/data/ALL_2015.csv"),select = c("YEAR","RSSDID","RSSDHCR"))
```

```{r}
yrs <- 2000:2022
sod <- list()
i=1

for(yr in yrs) {
  temp <- fread(paste0(data_path,paste0("SOD/data/ALL_",yr,".csv")),select = c("YEAR","RSSDID","RSSDHCR"))
  temp <- temp[!duplicated(temp)]
  sod[[i]] <- temp
  i=i+1
}

sod <- rbindlist(sod)
saveRDS(sod,"C:/Users/dimut/Downloads/rssd_rssdhcr_sod.rds")
```


# 2015 to 2019

```{r}
sod_2021 <- fread(paste0(data_path,"SOD/data/ALL_2015.csv"),select = c("UNINUMBR","CERT","RSSDID","ASSET","DEPSUM","DEPSUMBR","STCNTYBR","RSSDHCR","ZIPBR","SIMS_LATITUDE","SIMS_LONGITUDE","STCNTY"))
sod_2021[,DEPSUMBR:=str_remove_all(DEPSUMBR,",")]
sod_2021[,DEPSUMBR:=as.numeric(DEPSUMBR)]
sod_2021[,DEPSUM:=str_remove_all(DEPSUM,",")]
sod_2021[,DEPSUM:=as.numeric(DEPSUM)]

sod_2021[,ASSET:=str_remove_all(ASSET,",")]
sod_2021[,ASSET:=as.numeric(ASSET)]
sod_2021[,statefips:=floor(STCNTYBR/1000)]
sod_2021[,statefips:=str_pad(statefips,2,"left","0")]


sod_2022 <- fread(paste0(data_path,"SOD/data/ALL_2019.csv"),select = c("UNINUMBR","DEPSUMBR"))
sod_2022[,DEPSUMBR:=str_remove_all(DEPSUMBR,",")]
sod_2022[,DEPSUMBR:=as.numeric(DEPSUMBR)]
setnames(sod_2022,"DEPSUMBR","DEPSUMBR2")

sod <- merge(sod_2021,sod_2022,by="UNINUMBR")
sod[,change_in_deposits:= (DEPSUMBR2-DEPSUMBR)/DEPSUMBR]
sod[,deposit_share:=DEPSUMBR/DEPSUM]
sod <- sod[is.finite(change_in_deposits) ]#& deposit_share> quantile(sod$deposit_share,0.025,na.rm = T)]
sod <- sod[change_in_deposits > quantile(sod$change_in_deposits,0.01,na.rm=T) & change_in_deposits < quantile(sod$change_in_deposits,0.99,na.rm = T) ]

sod[,bank_size:=ifelse(ASSET<1e7,"1. Less than 10b",ifelse(ASSET<25e7,"2. 10 to 250b","3. More than 250b"))]
```




```{r}

branch_df <- place_visitor_wa[, lapply(.SD, mean, na.rm = TRUE), by = UNINUMBR, .SDcols = variables]
branch_df <- merge(branch_df,sod,by="UNINUMBR")
branch_df[,loss_deposits:=ifelse(change_in_deposits< 0,1,0)]

branch_df[,income_decile:=ntile(mean_family_income,10)]
branch_df[,education_decile:=ntile(college_or_higher_frac,10)]
branch_df[,age_decile:=ntile(median_age,10)]
branch_df[,white_decile:=ntile(white_fraction,10)]
branch_df[,dividend_decile:=ntile(dividend_frac,10)]
branch_df[,refinance_decile:=ntile(refinance_rate,10)]
branch_df[,distance_decile:=ntile(DISTANCE_FROM_HOME,10)]

branch_df[,bank_size2:=ifelse(bank_size=="1. Less than 10b","small","large")]

branch_df[,income_qt:=ntile(mean_family_income,4),by=bank_size2]
branch_df[,education_qt:=ntile(college_or_higher_frac,4),by=bank_size2]
branch_df[,age_qt:=ntile(median_age,4),by=bank_size2]
branch_df[,dividend_qt:=ntile(dividend_frac,4),by=bank_size2]
branch_df[,refinance_qt:=ntile(refinance_rate,4),by=bank_size2]
branch_df[,distance_qt:=ntile(DISTANCE_FROM_HOME,4),by=bank_size2]



branch_df[,ASSET:=ASSET.x]

branch_df[,sophisticated:=ifelse(education_qt>=3 & income_qt>=3 & dividend_qt>=3 & refinance_qt>=3,1,0)]

saveRDS(branch_df,paste0(data_path,"Dewey/reg_data/branch_df_2015_2019.rds"))
```



# 2021 to 2023

```{r}
sod_2021 <- fread(paste0(data_path,"SOD/data/ALL_2021.csv"),select = c("UNINUMBR","CERT","RSSDID","ASSET","DEPSUM","DEPSUMBR","STCNTYBR","RSSDHCR","ZIPBR","SIMS_LATITUDE","SIMS_LONGITUDE","STCNTY"))
sod_2021[,DEPSUMBR:=str_remove_all(DEPSUMBR,",")]
sod_2021[,DEPSUMBR:=as.numeric(DEPSUMBR)]
sod_2021[,DEPSUM:=str_remove_all(DEPSUM,",")]
sod_2021[,DEPSUM:=as.numeric(DEPSUM)]

sod_2021[,ASSET:=str_remove_all(ASSET,",")]
sod_2021[,ASSET:=as.numeric(ASSET)]
sod_2021[,statefips:=floor(STCNTYBR/1000)]
sod_2021[,statefips:=str_pad(statefips,2,"left","0")]


sod_2022 <- fread(paste0(data_path,"SOD/data/ALL_2023.csv"),select = c("UNINUMBR","DEPSUMBR"))
sod_2022[,DEPSUMBR:=str_remove_all(DEPSUMBR,",")]
sod_2022[,DEPSUMBR:=as.numeric(DEPSUMBR)]
setnames(sod_2022,"DEPSUMBR","DEPSUMBR2")

sod <- merge(sod_2021,sod_2022,by="UNINUMBR")
sod[,change_in_deposits:= (DEPSUMBR2-DEPSUMBR)/DEPSUMBR]
sod[,deposit_share:=DEPSUMBR/DEPSUM]
sod <- sod[is.finite(change_in_deposits) ]#& deposit_share> quantile(sod$deposit_share,0.025,na.rm = T)]
sod <- sod[change_in_deposits > quantile(sod$change_in_deposits,0.01,na.rm=T) & change_in_deposits < quantile(sod$change_in_deposits,0.99,na.rm = T) ]

sod[,bank_size:=ifelse(ASSET<1e7,"1. Less than 10b",ifelse(ASSET<25e7,"2. 10 to 250b","3. More than 250b"))]
```




```{r}

branch_df <- place_visitor_wa[, lapply(.SD, mean, na.rm = TRUE), by = UNINUMBR, .SDcols = variables]
branch_df <- merge(branch_df,sod,by="UNINUMBR")
branch_df[,loss_deposits:=ifelse(change_in_deposits< 0,1,0)]

branch_df[,income_decile:=ntile(mean_family_income,10)]
branch_df[,education_decile:=ntile(college_or_higher_frac,10)]
branch_df[,age_decile:=ntile(median_age,10)]
branch_df[,white_decile:=ntile(white_fraction,10)]
branch_df[,dividend_decile:=ntile(dividend_frac,10)]
branch_df[,refinance_decile:=ntile(refinance_rate,10)]
branch_df[,distance_decile:=ntile(DISTANCE_FROM_HOME,10)]

branch_df[,bank_size2:=ifelse(bank_size=="1. Less than 10b","small","large")]

branch_df[,income_qt:=ntile(mean_family_income,4),by=bank_size2]
branch_df[,education_qt:=ntile(college_or_higher_frac,4),by=bank_size2]
branch_df[,age_qt:=ntile(median_age,4),by=bank_size2]
branch_df[,dividend_qt:=ntile(dividend_frac,4),by=bank_size2]
branch_df[,refinance_qt:=ntile(refinance_rate,4),by=bank_size2]
branch_df[,distance_qt:=ntile(DISTANCE_FROM_HOME,4),by=bank_size2]



branch_df[,ASSET:=ASSET.x]

branch_df[,sophisticated:=ifelse(education_qt>=3 & income_qt>=3 & dividend_qt>=3 & refinance_qt>=3,1,0)]

saveRDS(branch_df,paste0(data_path,"Dewey/reg_data/branch_df_2021_2023.rds"))
```





# RateWatch Data
From: https://lsumail2-my.sharepoint.com/personal/rnarayan_lsu_edu/_layouts/15/onedrive.aspx?e=5%3A79ae71a0621e4c61bb5fa258ae118d1a&sharingv2=true&fromShare=true&at=9&CT=1723993488640&OR=OWA%2DNT%2DMail&CID=9e9eb62e%2D7d89%2Da6f4%2D513b%2D496f6d14ae36&cidOR=Client&id=%2Fpersonal%2Frnarayan%5Flsu%5Fedu%2FDocuments%2FData%2FRatewatch2024&FolderCTID=0x01200054D966B16334BB4CBD90E81846B012E5&view=0


```{r}
library(data.table)
library(lubridate)


folder <- "C:/Users/dimut/Downloads/"

rate_summary <- list()
i=1
for(yr in 2021:2024 ) {
  print(yr)
  df <- fread(paste0(folder,"DepositRateData",yr,".txt"))
  df[,DATESURVEYED:=as.Date(DATESURVEYED)]
  df[,qtr:=ceiling_date(DATESURVEYED, "quarter") - days(1)]    
  df[,qtr:=as.Date(qtr)]
  df <- df[PRODUCTDESCRIPTION=="12MCD10K"]
  rate_summary[[i]] <- df[,.(mean_apy=mean(APY,na.rm=T),median_apy=median(APY,na.rm=T)),by=.(qtr,PRD_TYP_JOIN,ACCOUNTNUMBER)]
  i=i+1
  
  rm(df)
  gc()
}


rate_summary <- rbindlist(rate_summary)
```

```{r}
acct_join <- fread("C:/Users/dimut/Downloads/Deposit_acct_join.txt")

rate_summary <- merge(rate_summary,acct_join,by.x=c("ACCOUNTNUMBER","PRD_TYP_JOIN"),by.y=c("ACCT_NBR_RT","PRD_TYP_JOIN"))

inst <- fread("C:/Users/dimut/Downloads/Deposit_InstitutionDetails.txt",select = c("ACCT_NBR","CERT_NBR","UNINUMBR","RSSD_ID"))

rate_summary <- merge(rate_summary,inst,by.x="ACCT_NBR_LOC",by.y="ACCT_NBR")
```

```{r}
saveRDS(rate_summary,paste0(data_path,"RateWatch/rate_summary_12MCD10K_2021_2024.rds"))
```

